# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
  schedule:
    - cron: "*/60 * * * *"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      uses: actions/setup-node@v2
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        args: install
        
    - name: Test Code
      uses: mujo-code/puppeteer-headful@16.6.0
      env:
        CI: "true"
      with:
        args: npm ci && node main.js
              
    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
            
